version: "3.9"

services:
  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: whatislove
      POSTGRES_PASSWORD: whatislove
      POSTGRES_DB: scheduler
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data